export const ROUTES = {
  SPLASH: "Splash",
  LOGIN: "Login",
  SIGNUP: "SignUp",
  OTP: "OTP",
  HOME: "Home",
  HISTORY: "History",
  PROFILE: "Profile",
  SELL_SCRAP: "SellScrap",
  SCHEDULE_PICKUP: "SchedulePickup",
  PICKUP_SUMMARY: "PickupSummary",
  SUCCESS: "Success",
  WALLET: "Wallet",
  NOTIFICATIONS: "Notifications",
  HELP: "Help",
  FAQ: "FAQ",
  RAISE_TICKET: "RaiseTicket",
  SETTINGS: "Settings",
  COMING_SOON: "ComingSoon",
};
