export const ROUTES = {
  // Auth
  SPLASH: "Splash",
  LOGIN: "Login",
  SIGNUP: "SignUp",
  OTP: "OTP",
  FORGOT_PASSWORD: "ForgotPassword",

  // Customer
  HOME: "Home",
  HISTORY: "History",
  PROFILE: "Profile",
  SELL_SCRAP: "SellScrap",
  SCHEDULE_PICKUP: "SchedulePickup",
  PICKUP_SUMMARY: "PickupSummary",
  SUCCESS: "Success",
  WALLET: "Wallet",
  NOTIFICATIONS: "Notifications",
  HELP: "Help",
  FAQ: "FAQ",
  RAISE_TICKET: "RaiseTicket",
  SETTINGS: "Settings",
  CHANGE_PASSWORD: "ChangePassword",
  CONTACT_SUPPORT: "ContactSupport",
  ABOUT_APP: "AboutApp",
  PRIVACY_POLICY: "PrivacyPolicy",
  TERMS: "Terms",
  LANGUAGE: "Language",
  COMING_SOON: "ComingSoon",
  EDIT_PROFILE: "EditProfile",
  MANAGE_ADDRESSES: "ManageAddresses",
  ADD_ADDRESS: "AddAddress",
  EDIT_ADDRESS: "EditAddress",
  ACCOUNT_SETTINGS: "AccountSettings",
  DELETE_ACCOUNT: "DeleteAccount",
  THEME: "Theme",
  NOTIFICATION_SETTINGS: "NotificationSettings",

  // Collector
  COLLECTOR_DASHBOARD: "CollectorDashboard",
  PICKUP_DETAILS: "PickupDetails",
  PICKUP_ACTION: "PickupAction",
  PICKUP_HISTORY: "PickupHistory",
  INVOICE: "Invoice",
  COLLECTOR_PROFILE: "CollectorProfile",
};
